### ISSUE TITLE
Does nnef have plan to release python .whl package?

### ISSUE THREAD

**Issue by joe8086** [KhronosGroup/NNEF-Tools#101]
Hi NNEF contributers.
Does nnef have plan to release python .whl package?
If nnef plan to support on local user must prepare build environment.
If cross platform, user may do different platform build environment prepare.
If user plan to deploy nnef on several targets, User need repeat do  environment setupt on several targets.
So I recommend nnef can provide .whl package for user to easy deploy on different target.

Thanks,
8086

**Comment by gyenesvi** [comment]
We do have plans to make pip installer, but the initial plan is to make it build from source automatically so that we don't have to provide versions for all platforms.
What build environment are you thinking about that needs preparation? C++ compiler?

**Comment by joe8086** [comment]
Hi Gyensvi,

Glad to know there are plan to support pip installer, and hope it will more quick to meet this done.

My build environment is mainly focus on Windows and Ubuntu platform.
If the pip install support these mainly develop platform, then we can do our job very happy.

Thanks.
8086
