### ISSUE TITLE
Pytorch and TVM support

### ISSUE THREAD

**Issue by Msabih** [KhronosGroup/NNEF-Tools#105]
Hi,

We are exploring the use of NNEF format to export model from pytorch directly or ONNX to NNEF and use it as a bridge to import it to TVM and optimize it further. Is it possible ? I read that recent commits were related to pytorch, how would it be possible to export the model to NNEF from pytorch ? Additionally, do you know of a way to import the NNEF model to TVM ?

**Comment by Msabih** [comment]
Hi thanks for the reply. At the moment, I have just started my Phd. Although I have prior expertise in deep learning on a higher level, I am not very proficient yet in deep learning compilation. However if we have an estimation of time, effort and expertise then it would be great. I could then analyze the use case for my research and consult my Phd supervisor.

**Comment by gyenesvi** [comment]
Thanks, let us know if there is some progress. For now, I would close the issue, as there is no action or our side.
