### ISSUE TITLE
nnef-validator catches error in gg19_flat.txt

### ISSUE THREAD

**Issue by jnorwood** [KhronosGroup/NNEF-Tools#11]
It isn't clear to me if the missing assignment to output1 is an error, or if it is supposed to be assigned automatically.   Anyway, the validator outputs an unexpected error message for this example from the github site.  The other examples passed.  This is using cygwin gcc compile.

jay@JayNorwood /cygdrive/c/nnef/NNEF-Tools/parser/cpp/build
$ ./bin/nnef-validator ../examples/vgg19_flat.txt
Parse error: [102:1] result 'output1' of operation 'vgg19' is not assigned

**Comment by gyenesvi** [comment]
The example has been fixed, can you please check and close the issue?

**Comment by jnorwood** [comment]
Yes works fine now.   

btw, the spec has fragments of a bnf grammar.  Is there a full bnf grammar definition file somewhere on github?
