### ISSUE TITLE
ModuleNotFoundError: No module named 'nnef'

### ISSUE THREAD

**Issue by y-katzav** [KhronosGroup/NNEF-Tools#112]
I'm trying to run nnef convertor from windows cmd folwing this instruction:

./nnef_tools/convert.py --input-format=nnef \
                        --output-format=tensorflow-pb \
                        --input-model=out/nnef/frozen_inception_v1/model.nnef.tgz \
                        --output-model=out/tensorflow-pb/frozen_inception_v1.pb

but I got a message error:
ModuleNotFoundError: No module named 'nnef' 

I configured my conda with windows cmd but it still didn't work

How I can solve it?

Thank's

**Comment by gyenesvi** [comment]
You have to install the NNEF module first, according to the first section in the readme:

https://github.com/KhronosGroup/NNEF-Tools/tree/master/nnef_tools#nnef-tools

**Comment by gyenesvi** [comment]
Can I close this issue?

**Comment by y-katzav** [comment]
Yes.

בתאריך יום ג׳, 4 בפבר׳ 2020, 10:58, מאת Viktor Gyenes ‏<
notifications@github.com>:
