### ISSUE TITLE
cannot build c++ parser

### ISSUE THREAD

**Issue by jianshitansuantong233** [KhronosGroup/NNEF-Tools#113]
After following the steps specified in README, I find no Makefile in the build directory, therefore I cannot run make command to build the c++ parser library.
A screenshot of contents of the build directory is shown below.
![Untitled](https://user-images.githubusercontent.com/45403873/72675529-4fd38d80-3a3a-11ea-9847-7362c4b7682e.png)

**Comment by gyenesvi** [comment]
Unfortunately I do no know too much about cmake, but the commands in the readme run fine on my computer. Are you saying that the `cmake ..` command run from the `build` folder executed properly but did not generate the makefile? I tried it now, and it generates a `Makefile` for me in the `build` folder, and then the `make` command also runs properly, generating the lib file..

**Comment by jianshitansuantong233** [comment]
Did you try it out on a Windows machine or Linux one?

**Comment by gyenesvi** [comment]
On Mac now, but it worked on Linux too. Did not try on Windows.

**Comment by jianshitansuantong233** [comment]
Ok, I did it on Windows, so I guess maybe that's the issue. 
Does the python parser do the same thing as c++ parser? If it is, then I will use that one and this missing Makefile wouldn't be an issue.

**Comment by gyenesvi** [comment]
Yes, the Python parser does the same thing (it is actually a wrapper around the C++ parser). When you install the Python package, it does compile the C++ code, although without using cmake.
