### ISSUE TITLE
Updating NNEF version

### ISSUE THREAD

**Issue by hansely** [KhronosGroup/NNEF-Tools#114]
Hi,
I'm having an issue while updating the nnef version.
I used the following command to update:

    cd parser/python
    python setup.py install

and verified that current version is 0.3. 

    Processing dependencies for nnef==0.3
    Finished processing dependencies for nnef==0.3

However, it seems like the updates haven't been applied.
When I remove the whole nnef library and reinstall from scratch, I was able to get the latest feature but when I update from previous version (0.2->0.3), I'm not getting them.
This happened to me also when I updated from ver 0.1->0.2 and I had to reinstall from scratch to solve the issue.

Are there any additional steps other than the above commands?

**Comment by gyenesvi** [comment]
I guess it may be some caching issue, I am not sure how setup exactly behaves when using `python setup.py install` to install a package manually (not via `pip install`). I didn't find any mechanism to force upgrade or something like that.

**Comment by hansely** [comment]
Then what are your recommended steps to update nnef version? 
Should I install nnef via  pip install?

**Comment by gyenesvi** [comment]
No, it is not possible to install via pip. For now, I guess the safest is what you did: uninstall and then setup. But in general, doing the setup alone is enough in my experience, are you suggesting that when there is a version change, the setup fails?

**Comment by hansely** [comment]
When there is a version change, setup script installs the latest version; but somehow the previous version is called instead. 
I'm not 100% sure if the issue belongs to your side or my side. Do you have a suggestion for testing this?

**Comment by gyenesvi** [comment]
I don't understand how you can have two version of the same package installed at the same time. Don't you accidentally have two python environments (in different system folders), and you install the NNEF package to one, but use the other?
