### ISSUE TITLE
Apparent bugs in execute_matmul

### ISSUE THREAD

**Issue by lxgo** [KhronosGroup/NNEF-Tools#115]
Hello

The following lines look like bugs to me:

In file  master/parser/cpp/include/nnef/runtime/execution.h:

Line 478: have
```
auto& C = op.inputs.get("C");
```
should be
```
auto& C = op.outputs.get("C");
```
Line 481: have
```
bool trB = op.attribs.get("transposeA").logical();
```
should be
```
bool trB = op.attribs.get("transposeB").logical();
```
Kind regards

**Comment by gyenesvi** [comment]
You are right, thanks for catching these, I have corrected it. (I believe it has not been caught before because matmul was tested as part of `linear` op)
