### ISSUE TITLE
Apparent minor bugs in format specifications in flat_parser

### ISSUE THREAD

**Issue by lxgo** [KhronosGroup/NNEF-Tools#117]
Hello

The following lines look like bugs to me.

In file `parser/cpp/include/nnef/flat/flat_parser.h`:

Line 232: have `(%s)`, should be `(%d)`:
```
throw Error(position, "left-hand-side item count must match result count of operation (%s)",
                (int)proto.resultCount());
```
Line 331: Trailing `(%u,%u)` doesn't correspond to any argument and should be removed:
```
throw Error(position, "duplicate arguments: parameter '%s' already assigned (%u,%u)",
                param->name().c_str());
```

Regards

**Comment by gyenesvi** [comment]
Right, thanks, corrected as well.
