### ISSUE TITLE
NNEF Model Converter Unsupported OP: LSTM

### ISSUE THREAD

**Issue by kobeyu** [KhronosGroup/NNEF-Tools#119]
Hi
I want to convert a onnx model to NNEF, 
But nnef model converter does not support op "LSTM",
Do you have plans to support it?

crnn onnx model: https://drive.google.com/file/d/1XjXJl_tNc4ABU8-N5gTWjqmf4MBQkUmB/view?usp=sharing
NNEF-tools: commit a92ad54529dbbb0981b3b10e3f27b19a969cf5f6

**Comment by gyenesvi** [comment]
Unfortunately it is not supported at the moment and we don't have ongoing plans for supporting it, maybe at some later point in the future.

What is your goal with using NNEF? What do you want to feed the converted model into?
