### ISSUE TITLE
build with gcc fails for missing isascii(x)

### ISSUE THREAD

**Issue by jnorwood** [KhronosGroup/NNEF-Tools#12]
This could be a gcc problem in cygwin.
I worked around by adding
#define isascii(cv) ((cv >= 0) && (cv <= 127))
in comp_parser.h

Then everything built, and I was able to validate using the test cases.

**Comment by gyenesvi** [comment]
The issue has been fixed as above, can you please check and close the issue if it is working well?

**Comment by jnorwood** [comment]
Yes, works fine now.  Thanks.
