### ISSUE TITLE
Issue with converting tools

### ISSUE THREAD

**Issue by jianshitansuantong233** [KhronosGroup/NNEF-Tools#122]
Hi, I have run into this issue when trying to convert from onnx to nnef. The error message is attached below:
![12c3ed813b087fc4bf86049cdfb4259](https://user-images.githubusercontent.com/45403873/82165084-9316ff00-9868-11ea-87c8-a050d1c8a749.png)

Does anyone know what is causing this?

**Comment by gyenesvi** [comment]
Your model seems to be old, and in that version of ONNX there was no 'steps' argument to 'slice' operator. I have added a fix, can you try now? (you'll have to reinstall the NNEF module)

**Comment by jianshitansuantong233** [comment]
yes it works. Thanks!
