### ISSUE TITLE
Build CPP parser code with VC2017

### ISSUE THREAD

**Issue by SvanKeulen** [KhronosGroup/NNEF-Tools#125]
Hi,
While trying the [latest cpp NNEF parser](https://github.com/KhronosGroup/NNEF-Tools/commit/d267053413769beb8c2157271209e95544c325ce#diff-30c9e7cf5b11f403018e304adcb0d8f4) (d267053), I notice several compiler errors.

cmake script creates project files without problems.
Are C++11 compatible compilers tested? If so, are results available somewhere?

Thanks!

**Environment:**
- Visual C++ 2017   00369-60000-00001-AA973
- Windows 10

**Errors:**
- 1>\nnef-tools-master\parser\cpp\include\nnef\runtime\ndrange.h(223): error C4576: a parenthesized type followed by an initializer list is a non-standard explicit type conversion syntax
- 1>\NNEF-Tools-master\parser\cpp\include\nnef/runtime/execution.h(59): error C4576: a parenthesized type followed by an initializer list is a non-standard explicit type conversion syntax
- 1>\NNEF-Tools-master\parser\cpp\include\nnef/runtime/execution.h(53): error C4576: a parenthesized type followed by an initializer list is a non-standard explicit type conversion syntax
- 1>\nnef-tools-master\parser\cpp\include\nnef\runtime\ndrange.h(218): error C4576: a parenthesized type followed by an initializer list is a non-standard explicit type conversion syntax

**Warnings:**
- 1>\NNEF-Tools-master\parser\cpp\include\nnef/runtime/execution.h(290): warning C4244: 'initializing': conversion from 'size_t' to 'T', possible loss of data
- 1>\NNEF-Tools-master\parser\cpp\include\nnef/runtime/execution.h(290): warning C4244: 'initializing': conversion from 'size_t' to 'const T', possible loss of data
- 1>\nnef-tools-master\parser\cpp\include\nnef\runtime\operations.h(33): warning C4244: '=': conversion from 'double' to 'T', possible loss of data

**Comment by gyenesvi** [comment]
Hi, I have pushed some fixes, it compiles with the `-std=c++11` flag on my side (clang). Can you test again now?

**Comment by SvanKeulen** [comment]
Hi, thanks for the quick response.
Yes, now compiles without errors.
Thank you.

**Comment by gyenesvi** [comment]
Welcome, thanks!
