### ISSUE TITLE
minor correction to README.md example

### ISSUE THREAD

**Issue by jnorwood** [KhronosGroup/NNEF-Tools#13]
just a small thing ...
The current cmake build creates bin/nnef-validator, while the README.md example uses bin/nnef-parser.

Example of execution under Linux:
````
$ cd <NNEF parser build directory>
$ ./bin/nnef-parser ../examples/googlenet_comp.txt --layers
$ ./bin/nnef-parser ../examples/googlenet_flat.txt
````

jay@JayNorwood /cygdrive/c/nnef/NNEF-Tools/parser/cpp/build
$ ls bin/nn*
bin/nnef-validator.exe

**Comment by gyenesvi** [comment]
Right, thanks for spotting that, I corrected the readme.
