### ISSUE TITLE
Incorrect parsing of tf.squeeze with default values

### ISSUE THREAD

**Issue by dvorotnev** [KhronosGroup/NNEF-Tools#135]
I try to convert simple python example:
```
import tensorflow as tf
import nnef_tools.io.tf.graphdef as graphdef


def testnet_squeeze():
    x = tf.placeholder(tf.float32, shape=[32, 1, 1, 3], name='input')
    return tf.squeeze(x)


tf.reset_default_graph()
with tf.Session() as sess:
    result = testnet_squeeze()
    sess.run(tf.global_variables_initializer())
    graphdef.save_default_graph("model.pb", session=sess, outputs={result: "output"})
```
with such commands:
```
python ./test.py
python -m nnef_tools.convert --input-format=tf --output-format=nnef --input-model=./model.pb --keep-io-names --output-model=model.nnef
```
The result of conversion is:
```
version 1.0;

graph G(input) -> (output)
{
    input = external<scalar>(shape = [32, 1, 1, 3]);
    squeeze1 = squeeze<scalar>(input, axes = []);
    output = copy(squeeze1);
}
```
but documented behavior of [tf.squeeze](https://www.tensorflow.org/versions/r1.15/api_docs/python/tf/squeeze) with empty `squeeze_dims` is to remove all dimensions of size 1. So, the conversion result should be:
```
version 1.0;

graph G(input) -> (output)
{
    input = external<scalar>(shape = [32, 1, 1, 3]);
    squeeze1 = squeeze<scalar>(input, axes = [1, 2]);
    output = copy(squeeze1);
}
```

**Comment by gyenesvi** [comment]
Seems correct, thanks for catching that!

**Comment by gyenesvi** [comment]
Note however that the fix did not cover all cases, namely the input may be transposed during the conversion process, in which case the input shape is already the transposed one, and that needs to be undone to be correct, since the input transposing is also undone in this transformation. I have posted a fix.
