### ISSUE TITLE
grammar file 

### ISSUE THREAD

**Issue by jnorwood** [KhronosGroup/NNEF-Tools#14]
The specification shows several fragments of bnf grammar definition, but I could not find a grammar file in github.  Is it possible to get the full definition?

**Comment by gyenesvi** [comment]
Basically, the full definition is just a concatenation of the fragments of grammar in the specification. Actually there are two grammars, one for the flat and one for the compositional syntax. So it is a good idea to summarize them and put them on Github.

**Comment by gyenesvi** [comment]
This is now included in the final spec released lately.

**Comment by jnorwood** [comment]
Thanks.   I noticed one change from using it with previous flattened output.  The semicolon is now not optional as assignment terminator.

the grammar and the processing of tuple-lvalue-expr could have  been simplified by making the parentheses non-optional.

**Comment by gyenesvi** [comment]
Yes, the semicolon is mandatory now. Furthermore, the parentheses on the tuple-rvalue-expr is also mandatory, but optional on the lvalue, as we did not see any benefit in that.

**Comment by jnorwood** [comment]
verified changes.
