### ISSUE TITLE
NNEF Reference Results

### ISSUE THREAD

**Issue by hansely** [KhronosGroup/NNEF-Tools#146]
Hi I am trying to compare the correctness of certain models. 
Does NNEF offer a runtime functionality where I can get the reference results for certain models?
Or does it always has to be converted to some other frameworks(pytorch/caffe/onnx) to run the inference and get the reference results?
If you guys can offer a reference result for the correctness purposes, that would be great.

**Comment by gyenesvi** [comment]
Yes, there are two ways to do that. If you need C++ code (CPU only), you can use the API here:

https://github.com/KhronosGroup/NNEF-Tools/blob/master/parser/cpp/include/nnef.h

Load the graph, and then use the `execute` function.

You can also use the `nnef_tools.execute` command-line tool, here:

https://github.com/KhronosGroup/NNEF-Tools/blob/master/nnef_tools/execute.py

This one executes an NNEF model using PyTorch. See the readme for more details:

https://github.com/KhronosGroup/NNEF-Tools/tree/master/nnef_tools#executing-a-model-and-saving-activations

**Comment by hansely** [comment]
Thanks for the info! I will close the issue now.
