### ISSUE TITLE
parser accepts multiple graph definitions from resnet_comp.txt

### ISSUE THREAD

**Issue by jnorwood** [KhronosGroup/NNEF-Tools#15]
The NNEF specification 3.2.4 grammar shows only a single graph definition in the grammar.  The resnet_comp.txt example has two graph definitions.  Is there a separate comp grammar spec describing acceptance of multiple graph definitions?

**Comment by gyenesvi** [comment]
True. We have experimented with allowing multiple graphs in the same file, but decided that it's not so important in the first version. However, it might be useful, and might be allowed in a later version. Let us know if you have a good use case when multiple graphs in the same file would be required.

**Comment by jnorwood** [comment]
I don't have current use for it.  I was just noting that the spec's grammar doesn't match the example, although your parser accepts it without error.
