### ISSUE TITLE
Outdated quantized models in model zoo 

### ISSUE THREAD

**Issue by TimotheeLeBerresonos** [KhronosGroup/NNEF-Tools#150]
The quantized models in the [model zoo](https://github.com/KhronosGroup/NNEF-Tools/tree/master/models#nnef-model-zoo) seem to be outdated. They are very different from the output of the current convert tool on the given input network.

For example, the models in the model zoo use a `tflite_quantize`  in the .quant file, while the output of the convert tool use a `zero_point_linear_quantize`.

The interpreter tool fails to execute the models that are currently in the model zoo. It works if I take the original tflite models and convert them myself using the convert tool. 

I tested Inception v1 and Mobilenet v1.

**Comment by gyenesvi** [comment]
Thanks for noting that, indeed, that has not been regenerated with the latest update that included fixes to the quantization data. Will regenerate them and upload.

**Comment by gyenesvi** [comment]
The quantized models in the model zoo have been updated with the output of the current converter tool, should be able to execute them with the interpreter tool.
