### ISSUE TITLE
Mismatch between specification and NNEF-tools in tensor item type

### ISSUE THREAD

**Issue by TimotheeLeBerresonos** [KhronosGroup/NNEF-Tools#151]
In the specification, the khronos item types are defined as: 

> • 0x0000 - float values in IEEE format, valid bits per item is 16, 32, 64.
> • 0x0001 - unsigned integer values, maximum bits per item is 64.
> • 0x0010 - quantized unsigned integer values, maximum bits per item is 64.
> • 0x0011 - quantized signed integer values, maximum bits per item is 64.
> • 0x0100 - signed integer values, maximum bits per item is 64.
> • 0x0101 - bool values, 1 bit or 8 bits (0 means false, non-zero means true)

In https://github.com/KhronosGroup/NNEF-Tools/blob/master/parser/python/nnef/binary.py, the item types are defined as:

```Python
class ItemType:    
    FLOAT = 0   
    UINT = 1    
    QUINT = 2    
    QINT = 3   
    INT = 4    
    BOOL = 5
```

This mismatch originates from #123 , where its seems 0x10 was converted to 2 and so on.

**Comment by gyenesvi** [comment]
Not sure I understand what mismatch you are referring to, since `0x10 == 2`. To me all hex values seem to match their decimal counterparts.

**Comment by TimotheeLeBerresonos** [comment]
I think `0x10 == 16` usually. That is the case in python at least, so the behavior changed after #123 .

**Comment by gyenesvi** [comment]
Oh, your are right. I mistook them for binary values. Actually, that is what they are meant to be, otherwise, the values would be quite scattered. This is an error in the spec, not the tools, which needs a bit of consideration to fix.

**Comment by TimotheeLeBerresonos** [comment]
Alright, thank you !

**Comment by gyenesvi** [comment]
The spec has been updated to clarify that the literals are meant to be binary.
