### ISSUE TITLE
Converting TfLite model to NNEF, SQUEEZE attribute error

### ISSUE THREAD

**Issue by Legerdemainist** [KhronosGroup/NNEF-Tools#153]
I am trying to convert a derivative of MobileNetV2, I have the .tflite file however when I'm trying to convert it I get the following error
`Could not evaluate attribute 'dtype' while converting operator 'SQUEEZE'; NameError: name 'T' is not defined`
This is the converter call I use
`python3 -m nnef_tools.convert --input-format tflite --output-format nnef --input-model model.tflite  --output-model model.nnef`

**Comment by gyenesvi** [comment]
I have pushed a fix for the converter, can you try again now and let me know if it works?

**Comment by Legerdemainist** [comment]
Thank you for your quick help!
I grabbed the newest master and tried it, however, now the `io/nnef/writer.py` is giving me the following attribute error:
`AttributeError: module 'nnef' has no attribute 'format_version'`

**Comment by gyenesvi** [comment]
It seems that your nnef package is outdated, probably from a previous install. Could you try uninstalling it from pip and running setup.py again for the nnef package (not for nnef_tools)?

**Comment by Legerdemainist** [comment]
Seems to be working now. Thank you for your help!
