### ISSUE TITLE
ONNX to NNEF: NameError: name 'split' is not defined

### ISSUE THREAD

**Issue by Christof23** [KhronosGroup/NNEF-Tools#161]
Hi, I'm getting a `Could not evaluate attribute 'ratios' while converting operator 'Split'; NameError: name 'split' is not defined` error when converting a yolov5s.onnx model to NNEF format. Any suggestions about how to fix this issue would be greatly appreciated.

**Comment by gyenesvi** [comment]
Hi, it seems that the newer versions of the Split operator in ONNX can also take the split ratios as a dynamic tensor instead of a static attribute. I have pushed a fix for this case, can you try again after pulling the latest code? BTW, exporting the ONNX model with an older opset version could also help in such cases.

**Comment by Christof23** [comment]
Hi @gyenesvi, thank you very much for your help with this issue. 

I've updated my local repo which fixes the split error. The model now exports to a directory, but returns a `Read-only file system: '/model.24'` message. When I import the tgz compressed nnef model into tract I get a `Error: Resource graph.nnef was not found in the model`, although in the actual directory the `graph.nnef` file is present.

**Comment by gyenesvi** [comment]
Hmm, I have no idea what that read-only issue could be, is '/model.24' one of the weights? Do you get this error during conversion? And what do you use to import the model? The python package in this repo, or something else? Did you try without tgz compression? Does the graph.nnef have seemingly proper contents inside if you open with a text editor?

**Comment by gyenesvi** [comment]
Indeed the nnef file looks reasonable. But did you get the readonly error while conerting or while reading it in?
That reader you reference is not part of this toolset, so I cannot help with that one unfortunately. You could try reading back the NNEF model with these python tools to check if it works. For example you could just try to conver it back to ONNX or even just to NNEF, you should just get the same file again but tests the reader.

**Comment by gyenesvi** [comment]
@Christof23 any update on this? Can I close it?
