### ISSUE TITLE
specification of negative numeric literals

### ISSUE THREAD

**Issue by jnorwood** [KhronosGroup/NNEF-Tools#18]
The specification doesn't explicitly state that a numeric literal can have an optional preceding sign on the integer part, as it states for the exponent.  It seems to me that this would be needed in the flat parsing, It appears that it would be handled as a unary minus expression, but it isn't clear if expressions are in general going to be handled by the flat parsing.  

This is another case for having documents for both the flat and composite specs.

**Comment by gyenesvi** [comment]
I close this issue and continue discussing this in the NNEF-Docs repo:

https://github.com/KhronosGroup/NNEF-Docs/issues/4
