### ISSUE TITLE
Onnx

### ISSUE THREAD

**Issue by bhack** [KhronosGroup/NNEF-Tools#2]
What relationships do you want to maintain with [ONNX](http://onnx.ai)?

**Comment by gyenesvi** [comment]
We are open to collaboration with ONNX. It is good to see that others also work on similar solutions, it shows that there is a real industry need in this area. I believe the two groups have overlapping goals but also there are differences in the approaches and details. It would be good to share more about our approaches and leverage each other's expertise in the field.
