### ISSUE TITLE
VS2017 compiler doesn't accept some NNEF tool code

### ISSUE THREAD

**Issue by jnorwood** [KhronosGroup/NNEF-Tools#21]
In several places, for example in makeBinaryOpArgs, there is use of a form of initializing a return struct value that isn't accepted in VS2017.

   //return (std::vector<Argument>)
   //         {
   //             Argument("x", left),
   //             Argument("y", right),
   //         };
 
replaced with
			std::vector<Argument> rv { Argument("x",left),Argument("y", right) };
			return rv;

**Comment by jnorwood** [comment]
github leaves out  code within angle brackets ...

			std::vector <Argument> rv { Argument("x",left),Argument("y", right) };
			return rv;

   //return (std::vector\<Argument>)
   //         {
   //             Argument("x", left),
   //             Argument("y", right),
   //         };

` `

**Comment by gyenesvi** [comment]
You are right about this, we have also encountered some pieces of code that don't compile with VS (and has been fixed in a private repo not yet merged here). Can you propose a pull request with all the modifications that make it compile on your side?

**Comment by jnorwood** [comment]
Looks like the April 5 commit already fixed this...
