### ISSUE TITLE
tf2nnef.py out of sync with tensorflow 1.5

### ISSUE THREAD

**Issue by jnorwood** [KhronosGroup/NNEF-Tools#22]
I'm  trying the example that exports nnef files from tensorflow, using python3.
I added this, which wasn't in the example...
import importlib
foo=importlib.machinery.SourceFileLoader("tf2nnef", "/home/xx/.../src/tf2nnef.py")

The loading fails at line 1057 of tf2nnef.py, which is apparently expecting tensorflow.python.ops.gen_math_ops to include a 'sub'.  I see in the 1.5 tensorflow that there is a 'subtract' in math_ops, but no 'sub', so I'm guessing that's the problem.

**Comment by jnorwood** [comment]
There were four... 
_sub, _mul,  _neg,  _real_div

all just needed to remove the leading underscore.  Then it loads.

**Comment by gyenesvi** [comment]
Thanks, we have encountered this problem as well (the above method names have been changed in TF 1.5), fix is underway.

**Comment by gyenesvi** [comment]
This has been fixed, although as we see this is only starting from version 1.7. Did you say it broke for you in version 1.5 or that it still worked in version 1.5 and not later? 
Can you check if it works now?

**Comment by jnorwood** [comment]
you are correct.  My installed tensorflow version is 1.8.  I verified the
new tf2nnef.py works with my modified sample_export.py.

On Thu, May 24, 2018 04:50, Viktor Gyenes wrote:
This has been fixed, although as we see this is only starting from version
1.7. Did you say it broke for you in version 1.5 or that it still worked
in version 1.5 and not later?
Can you check if it works now?

**Comment by jnorwood** [comment]
verified the new fix works.
