### ISSUE TITLE
caffe export to nnef on ubuntu 18.04

### ISSUE THREAD

**Issue by jnorwood** [KhronosGroup/NNEF-Tools#24]
There is a simplified installation of caffe for ubuntu 18.04, with the prebuilt binaries being installed in /usr/bin.  (see http://caffe.berkeleyvision.org/install_apt.html )

The simple install is just "sudo apt install caffe-cpu", which is much easier than having to build everything.

With that prebuilt installation, the export of caffe to NNEF example (provided in the NNEF-Tools) requires CAFFE_BIN_FOLDER to be /usr/bin, but also requires the "upgrade_net_proto_text.bin" to be changed to "upgrade_net_proto_text" in the export_from_caffe.py script.

It's a bit of work to figure this out, so maybe add something to the README

**Comment by gyenesvi** [comment]
This seems to be related to/the issue same as #16, right?

**Comment by jnorwood** [comment]
It is possible they are related if the installation in #16  installed Caffe with the precompiled binary installation, which installs everything in /usr/bin.  With either precompiled binaries or with the source installation, you do need to set the CAFFE_BIN_FOLDER, it just isn't clear from the README what that should be, since the directions are related to the source installation.  Beyond that, the upgrade_net_proto_text.bin file apparently does not exist with the .bin suffix, so the user needs to go into the script and fix that name (remove the suffix) in the case of the precompiled binary installation.

I don't recall the exact error messages I got when attempting to execute the script, and if they were similar to those reported in 16.   The messages weren't too hard to figure out, but an extra note in the README would help, especially since I suspect many will install the precompiled binaries, since that is such a pain-free process relative to my experience with resolving all the dependencies to build with the sources.

**Comment by jnorwood** [comment]
Looking at #16  again, it appears to me that the state=TRAIN value in the caffe.proto is intended to enable use of sections such as Accuracy.  It appears to me that the person changed the Accuracy section enum tag to TEST while attempting to manually convert the training .prototxt file for use in inference.  

The error trace messages there don't appear to be what I recall in this reported instance.

**Comment by gyenesvi** [comment]
We have committed a fix for this issue, can you check if it works on your side?

**Comment by jnorwood** [comment]
I checked out your commit and it works fine now, thank you.  I'll close this issue.


a couple of notes on using python3 ... some of the instructions change, for example:
 
sudo apt install python3-pip
sudo python3 setup.py install
