### ISSUE TITLE
There is a question about the correctness of converter output result.

### ISSUE THREAD

**Issue by tylerchen0619** [KhronosGroup/NNEF-Tools#25]
Hi,

There is a question about the correctness of converter output result.
I got the error message that validated the graph.nnef by the validator.

Herer is the error message.
-----------------------------------
Parse error: [55:11] incompatible tensor shapes in binary operation ([4096,10] vs [10,1])
-----------------------------------
The full validated log, please see the attachment "error.log".  
[error.log](https://github.com/KhronosGroup/NNEF-Tools/files/2053121/error.log)

If the network model file can be executed correctly by TensorFlow, 
but the graph.nnef got the validated error. 
Then, how to fix the situation.

Also, I attach the files that include network model and graph.nnef to here.
[d200_alexnet_export.py.txt](https://github.com/KhronosGroup/NNEF-Tools/files/2053123/d200_alexnet_export.py.txt)
[graph.nnef.txt](https://github.com/KhronosGroup/NNEF-Tools/files/2053472/graph.nnef.txt)

Thanks.

**Comment by gyenesvi** [comment]
Hi,

Indeed, this was a problem with the exporter, we have fixed it just now. Can you try exporting it again from TensorFlow with the updated exporter and try validating it afterwards?

Thanks

**Comment by tylerchen0619** [comment]
Hi, 

Thank you very much. The result shows a correct message that got the "Parse succeeded".

By the way, I try to validate all options for the validator, the"--atomic" option shows that "Segmentation fault (core dumped)".

Maybe we can get better information.

Thanks.

**Comment by gyenesvi** [comment]
Thanks, you are right, if you just write --atomic that's an error (and it should not result in a segfault). You have to write a list of operations after it, which you want to add or remove from the list of atomics. For example --atomics "+op1 -op2" adds op1 and removes op1. By default all operations defined in the standard are atomics.

The coming update of the parser will handle the segmentation fault and give a proper error message.

For now I close this issue as the original issue has been fixed.
