### ISSUE TITLE
transfer weights from training file to deploy using conversion tool transfers 0 as weights

### ISSUE THREAD

**Issue by jnorwood** [KhronosGroup/NNEF-Tools#35]
I attempted to use the --weights parameter to specify the squeezenet*.caffemodel as the source for the weights for deploy.prototxt or for train_val.prototxt.  The first case says Success, but has all 0.0 weight and bias values.  The second case fails with some error.  In caffe I can see that there are non-zero weight and bias values.  Not clear what the error is, since it conversion reports success.  Perhaps it is ignoring the --weights file specification?
```
import caffe
import numpy
nnet = caffe.Net("deploy.prototxt",1, weights= "squeezenet_v1.1.caffemodel")
net.params['conv1'][0].data[...] # weights
net.params['conv1'][1].data[...] # biases 
```

**Comment by garaczit** [comment]
I've tried both prototxts, and both worked fine. But if the name of the weight file is misspelled, the converter treats it as if no weight file was given and initializes a new caffemodel with the same name as the prototxt. This might have happened in your first case, creating a zero-initialized network. It is a silent failure case, we will change this behavior to be more user-friendly and less misleading.

For the second case with the train_val.prototxt, I assume the Caffe framework might complain about not finding the train database file ("examples/imagenet/ilsvrc12_train_lmdb").
In this case, the error you got looks as follows: 
"Check failed: mdb_status == 0 (2 vs. 0) No such file or directory"
Is this right?

**Comment by jnorwood** [comment]
on train_val.prototxt, yes, it is as your error messages shows, at db_lmdb.hpp:15

on the deploy.prototxt with the squeezenet*.caffemodel, I think you are correct.  Repeating it, I get non-zero data now in the conv1 bias.dat,  so I must have typed the weights name wrong previously.

I'll close this out.
