### ISSUE TITLE
support for pipelined processing of resnet type graphs with bypass loops

### ISSUE THREAD

**Issue by jnorwood** [KhronosGroup/NNEF-Tools#39]
If  you attempt to slice up the resnet graph for pipelined processing, it appears to me that implies some type of per layer identity operations for the bypass loops in the graph.

I'm wondering if the nnef model translation tools provide any  support for migrating models for use in  pipelined processing.   It seems to me that would call for support of a circular buffer  fragment.

A similar issue would be for support of representing ping-pong double buffering. 

I suspect these are considered implementation details, but it seems to me those aspects of the network design are  also important to persist and translate, so I'm wondering if nnef tools will support that type of info.    Thanks.

**Comment by gyenesvi** [comment]
Can you elaborate on what you exactly mean by pipelined processing and slicing up the model? How would that change the network description? What would need to be indicated in the description? And how would the designer of the network possibly know that?

As you say that this is probably implementation detail. In a sense, the goal of the NNEF description is to abstract away all that detail and leave optimizations to the compilation process for the target device. NNEF only describes the semantics of the computation. Even hinting would only be possible if the designer of the network could decide what the hint should be, which may dependent on the target device?

**Comment by jnorwood** [comment]
Pipelined processing of the graph means that a processor  is associated with the operations of a layer, and can begin processing of the next streamed input as soon as it finishes its task on the single layer.  By slicing, I just mean the assignment of processor resources to each layer of the graph.  The description would need to explicitly show  the implied identity delay operations that would  be required to maintain synchronization at the summing point at the end of  the skip path ( I called it the bypass loop).

This paper has a description of fpga processing of a resnet graph.  In B:5) of the hardware description, they refer to it is skip connection data.  In order to keep it synchronized with the convolution data at the summation point, the skip effectively implies an identity delay operation for each convolution operation.  
In order to model this correctly, in terms of memory and other resource requirements, the graph should really be modified to show the required delay operations.  How those are implemented efficiently is more of an implementation detail, but what I'm more interested in is if the graph that gets emitted can be expanded to explicitly show these required layers.   That representation would be required for design of an  fpga implementation, as described in the paper.  
https://arxiv.org/pdf/1708.00052.pdf
> In order to sum the skip connection data and the corresponding
convolution result, skip connection inputs are buffered to
compensate for delay created by the intermediate convolutional
layer in a “regular” path.

>

**Comment by gyenesvi** [comment]
As far as I understand from your description, the skip connections need to be mapped to delay operations, which would mean inserting explicit `delay` operations into the network that semantically do nothing, just copy their input to their output. It would be possible to use the `copy` operation available in NNEF (called `idn` for identity in the provisional), or to declare a custom fragment called `delay` just for this purpose. Would that be a satisfactory solution?

**Comment by jnorwood** [comment]
Yes, the idn operation is all that is necessary to represent the delay stages.   My question is if there is any support or any convention for making that type of delay assumption explicit in a graph translation.

**Comment by gyenesvi** [comment]
No, there is no such convention. I'd say it would be possible to define a new operation that expresses that delay, but otherwise is just equivalent to a copy. I believe `nop` is often used to express delay, so maybe something like:

```
fragment nop( input: tensor ) -> ( output: tensor )
{
     output = input;
}
```

would do. The semantics of the operation `nop` would be that it expresses that it should not be optimized away, but it's an active time spent with doing nothing, os it should be used (as opposed to copy) when expressing such a synchronization is required. Is this something you think about? So a resnet shortcut construction would be expressed as:

```
fragment resnet_unit( input: tensor, ... ) -> ( output: tensor )
{
    filtered = conv(input, ...);
    shortcut = nop(input);
    output = filtered + shortcut;
}
```

**Comment by jnorwood** [comment]
With  pipelined parallelism there would be an implied copy, since there is new input being processed by each layer of the graph for each execution phase, including by the layer that feeds into the skip edge.    The NNEF graph implies that the operation statements are executed in order, and so the merge operation will follow execution of the skipped convolution operations.

**Comment by gyenesvi** [comment]
So could the above code properly express what you talk about? Or is there something still missing?

**Comment by jnorwood** [comment]
yes, an IDN node per layer would work.  A single Delay node with a delay count and an array of buffers with count equal to the skipped layers +1 would be closer to the circular buffer implementation.

I'll close this out.  You might consider it as an option, since it seems like a common feature that will be required in model migration for fpga targets.
