### ISSUE TITLE
Caffe to NNEF converter is producing incorrect NNEF structure file

### ISSUE THREAD

**Issue by rgiduthuri** [KhronosGroup/NNEF-Tools#4]
Below is the example that I used for this test: https://github.com/BVLC/caffe/blob/master/examples/cifar10/cifar10_quick.prototxt

1. The caffe export script is using 'deploy.desc' filename instead of 'graph.nnef' filename specified in Section 5.1 of the spec.
2. Generated text is not valid per the nnef-validator.

**Comment by gyenesvi** [comment]
You are right that the file name is incorrect, that's an easy fix.

However, I cannot see the problem with the generated text. Can you post the error message? On my side the validator accepts it. What are the command-line arguments for the validator execution? Doesn't it fail upon checking the data files and it may be related to the other issue?

**Comment by rgiduthuri** [comment]
With the most recent commit, I see that it is creating 'graph.nnef' file instead of 'deploy.desc'.

One issue is still left. The converter is generating 5L which is not legal syntax.
````
conv1_filter = variable(label = 'conv1/filter', shape = [32, 3, 5L, 5L])
````

**Comment by gyenesvi** [comment]
Added a branch `fix_int_literal` to treat this issue, can you test it on your side?

**Comment by rgiduthuri** [comment]
This seems to fix the reported issue. Thanks.
