### ISSUE TITLE
Can't correctly fill TensorHeader

### ISSUE THREAD

**Issue by igsha** [KhronosGroup/NNEF-Tools#42]
I use `TensorHeader` struct to parse dat-files of tensor weights coefficients.
Its definition is in file `parser/cpp/common/binary.h`.

This is my code to write tensor weights:
```c++
std::ofstream file(filename, std::ios::binary);
nnef::Shape nnef_shape(...);
...

nnef::TensorHeader header;
size_t version[] = {1, 0};
nnef::fill_tensor_header(header, version, nnef_shape.rank(), nnef_shape.extents(), 8 * sizeof(float), nnef::TensorHeader::Float);

file.write(reinterpret_cast<const char*>(&header), sizeof(header));
file.write(reinterpret_cast<const char*>(data), sizeof(float) * nnef_shape.volume());
```
But it writes incomplete header: there is no `extents` (dimentsions) values in the file.
That's why I have to add something like this in my code (before calling `file.write`):
```c++
std::copy_n(nnef_shape.extents(), nnef.shape.rank(), header.extents);
```
It seems there is some problem in `nnef::fill_tensor_header` function.

**Comment by gyenesvi** [comment]
You are right, there was a bug in the copy, fixed just now.

**Comment by igsha** [comment]
Checked your last commit. It works. Thanks!
