### ISSUE TITLE
B,C,H,W vs B,H,W,C in TensorFlow to NNEF conversions

### ISSUE THREAD

**Issue by jnorwood** [KhronosGroup/NNEF-Tools#44]
How do  the TensorFlow to NNEF conversion scripts handle the Tensorflow B,H,W,C Tensor definitions?  Are the graph shape parameters and input files converted to B,C,H,W order by the NNEF conversion scripts, or left in the order defined in TensorFlow?

**Comment by gyenesvi** [comment]
They are converted to BCHW order where required, depending on the operations that consume them.
