### ISSUE TITLE
nnef_to_tf  transposes variables [2,3,1,0] ??

### ISSUE THREAD

**Issue by jnorwood** [KhronosGroup/NNEF-Tools#45]
I have some NNEF variable shapes [64,32,1,1]  in the nnef graph, and am using  nnef_to_tf, without specifying the weight/filter files.
I was expecting [64,1,1,32], which would be the tf NHWC .
but instead got [1,1,32,64] in the generated python file for tf.   

I'm  just providing the statements, such as
filter2 = variable(shape=[64,32,1,1], label = 'conv2/filter');

What causes the nnef_to_tf to do a [2,3,1,0] transpose in this case?  With the -v option, I see that  transpose commenting the variable line. 
I'll attach a small sample that demonstrates it.
[graph3.txt](https://github.com/KhronosGroup/NNEF-Tools/files/2417493/graph3.txt)

**Comment by gyenesvi** [comment]
That is because in TF, the dimension order for _filter_ in case of a conv2d is not NHWC, (as for the input), but instead HWCN, and that is exactly what you get. See the documentation of conv2d here:

https://www.tensorflow.org/api_docs/python/tf/nn/conv2d

The relevant part is: "Given an input tensor of shape [batch, in_height, in_width, in_channels] and a filter / kernel tensor of shape [filter_height, filter_width, in_channels, out_channels] ..."

**Comment by jnorwood** [comment]
I looked at it further.  Even in their non-quantized mobilenet 223 model, the frozen.pb conv2d0 weights are in [3,3,3,32] shape, which matches the HWCN in the doc, while the .tflite persistence model in the same group has [32,3,3,3] for the weights shape.   I filed an issue there.   I don't know at this point if their tflite interpreter has a different requirements for the shape, or if their tflite format somewhere specifies a fixed weight shape, or if they simply wrote out the shape in the wrong order.  I guess I can go dig through their python code...
https://github.com/tensorflow/tensorflow/issues/22540

**Comment by gyenesvi** [comment]
I could also easily imagine that TFLite has as different format, to me it makes sense to have the same format for weights as for activations.

**Comment by jnorwood** [comment]
From their positive comments, it appears to me they prefer the tflite flatbuffer files. Positive comments about the simpler loader, since data is uncompressed.  Also they mentioned it is capable of access as a memory mapped file, although there are some discussions that indicate it may not be a well supported feature.
https://github.com/google/flatbuffers/issues/4682

The tflite project has some compatibility limitations, though, and maybe this weight shape thing is related.   I think they should resolve that.

I'm going to close this, since you aren't supporting the tflite currently.  Your app matches the .pb data.
It isn't clear to me if they have any quantized inference models available that aren't in the tflite flatbuffer format, though, so if you are planning to support tf quantized models, you would also need to handle their different weight shape.

**Comment by jnorwood** [comment]
Someone posted a link to the tflite code that acknowledges the differences for the weight shapes, and other differences.  I can't tell from he comments if they plan to resolve this.  
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/lite/toco/model.h#L162-L172
  kCR,       // column-major matrix storage order. Our standard.
  kRC,       // row-major matrix storage order. TensorFlow default.
  kOHWI,     // Our standard for conv weights
  kHWIO,     // TensorFlow conv weights
  k1HWO,     // Our standard for DepthwiseConv weights
  kHWIM,     // TensorFlow DepthwiseConv weights
  kNHWC,     // TensorFlow activations
  kHWOI,     // TensorFlow back-prop conv weights
