### ISSUE TITLE
tensorflow padding conversion vs caffe

### ISSUE THREAD

**Issue by jnorwood** [KhronosGroup/NNEF-Tools#46]
I see stated in the tensorflow docs that TensorFlow's implementation of padding comes up with different values than Caffe's implementation.  Does NNEF comply with the source model's padding values, or does it substitute its own padding values during the conversion?

https://www.tensorflow.org/api_guides/python/nn#Convolution

> For example, when pad_along_height is 5, we pad 2 pixels at the top and 3 pixels at the bottom. Note that this is different from existing libraries such as cuDNN and Caffe, which explicitly specify the number of padded pixels and always pad the same number of pixels on both sides.

**Comment by gyenesvi** [comment]
Yes, this is accounted for in NNEF. Auto-padding (`padding = []`) is defined as in TensorFlow (and other frameworks that do auto-padding). When you specify explicit padding values, you can specify whatever top/bottom values you want, and if you specify it to be the same value, you get exactly what Caffe does.

**Comment by jnorwood** [comment]
ok, thanks.
