### ISSUE TITLE
scalar and tensor<scalar>

### ISSUE THREAD

**Issue by asdor** [KhronosGroup/NNEF-Tools#52]
Hello. I have a problem with a function clamp in nnef:
```
fragment clamp( x: tensor<scalar>, a: tensor<scalar>, b: tensor<scalar> )
-> ( y: tensor<scalar> );
```
In function signature it is said, that parameters `a` and `b` are type of `tensor<scalar> `.  
But if i want to convert the next code from tensorflow to nnef:
```
def test_clamp():
    x = tf.constant([-5, 4, 6], shape=[3])

    ans = tf.clip_by_value(x, 0, 5)

    return {"ans": ans}
```
I get the next graph.nnef:
```
graph test_clamp(  ) -> ( ans )
{
    const1 = constant<integer>(shape = [3], value = [-5, 4, 6]);
    ans = clamp(x = const1, a = 0.0, b = 5.0);
}
```
Here, `a` and `b` are scalars, not tensors<scalar>. That begs the question - whether scalar is a 0-D tensor, like in tensorflow? Or not?

**Comment by gyenesvi** [comment]
Yes, scalars are 0-D tensors, so it can be used for a and b.

However, the problem with the above code, is that the constant `x` is an integer tensor, not a scalar tensor, as `clamp` expects (and there is no automatic conversion). You should either add `dtype=tf.float32` or use `[-5.0, 4.0, 6.0]` in `tf.constant`.

**Comment by asdor** [comment]
Yes, that's my fault with dtype, but if i try to parse:
```
def test_clamp():
    x = tf.constant([-5, 4, 6], shape=[3], dtype=tf.float32)
    ans = tf.clip_by_value(x, 0, 5)

    return {"ans": ans}
```
I get the next graph.nnef:
```
graph test_clamp(  ) -> ( ans )
{
    const1 = constant<scalar>(shape = [3], value = [-5.0, 4.0, 6.0]);
    ans = clamp(x = const1, a = 0.0, b = 5.0);
}
```
Problem in the nnef, in type of `a` and `b`. I expect, that they are tensors, but they are scalars. Is it right behavior?

**Comment by gyenesvi** [comment]
Yes that is the right behaviour, as I said above.

But if you try to parse this, it will fail, because the graph does no have any inputs..

**Comment by asdor** [comment]
But documentation said, that tensor must have 2 or more dimensions.
![default](https://user-images.githubusercontent.com/31508059/48062190-5c235000-e1d2-11e8-80c0-a46b8cb83591.png)

**Comment by gyenesvi** [comment]
No, the documentation does not say that every tensor has to have 2 or more dimensions. It says that every implementation has to support at least 2 dimensional tensors, which is a completely different thing.

**Comment by asdor** [comment]
Thank you for your answer!
