### ISSUE TITLE
Clarify Au-Zone Technologies, Inc. code licensing

### ISSUE THREAD

**Issue by Echelon9** [KhronosGroup/NNEF-Tools#53]
Can the license for the code in `au-zone/` please be clarified?

* Reviewing this repository and the convertor code contributed by Au-Zone Technologies, Inc. in `au-zone/`, the Apache License, Version 2.0 *appears* to be the intention.
* This is true within the source files, except for the contradictory comment at https://github.com/KhronosGroup/NNEF-Tools/blob/master/au-zone/setup.py#L36 which says "PROPRIETARY".

Can this licensing inconsistency be corrected by the individuals who hold copyright?

**Comment by gyenesvi** [comment]
Indeed, the Apache 2.0 is the intended one, I'll get the proprietary thing sorted out.

**Comment by gyenesvi** [comment]
I have fixed `setup.py`, changed license to Apache 2.0.

**Comment by Echelon9** [comment]
Great, closing!
