### ISSUE TITLE
Pre-trained Models in NNEF Format

### ISSUE THREAD

**Issue by kiritigowda** [KhronosGroup/NNEF-Tools#59]
Are some of the widely used networks for benchmarking available online in NNEF format to be used freely and shared.

# Models
* GoogleNet
* InceptionV4
* ResNet 50
* ResNet 101
* ResNet 152
* VGGNet 16
* VGGNet 19

**Comment by gyenesvi** [comment]
Not yet publicly, as the copyright implications are not clearly understood.

**Comment by gyenesvi** [comment]
This is now live in the 'models' folder.
