### ISSUE TITLE
protobuf format for nnef

### ISSUE THREAD

**Issue by jnorwood** [KhronosGroup/NNEF-Tools#63]
The Netron graph display tool is very useful, and they support many formats.   It appears to me that if NNEF had a protobuf or flatbuffer format then it would not be a big issue to request that they add support for your model.   Has there been any discussion about creating a protobuf format?

**Comment by gyenesvi** [comment]
It would technically be possible to convert NNEF to a protobuf format, however, keeping up two format definitions (one textual and one binary) is duplicating a lot of work, and would not add too much value (it is not worth just for the sake of visualization). There are tons of similar protobuf based formats out there, and I don't believe there is a need for one more.

**Comment by jnorwood** [comment]
I was thinking that it would be a good idea to effectively model in the protobuf format what you are using as your parser structs and containers.   

For model to model translation, it would be cleaner to just be working with two protobufs, and then have the  protobuf to text conversion be done as a separate step.  My current tflite_to_nnef conversions, for example, are processing flatbuffer tflite, but then must output to text files.

The protobuf and flatbuffer  descriptions also suggest ways of maintaining some level of backward compatibility, deprecation procedures,  and at least a hope of automating model migrations when updates are needed.  That seems to be a plus.  Tensorflow provides some scripts for migrating your models, for example.

**Comment by gyenesvi** [comment]
In the beginning of designing NNEF, a textual format seemed more adequate as the assumption was that it will be important to be able to describe parameter expressions (like math formulas) and compound operations, which are just like procedures in a programming language (with a signature of typed formal parameters and a body which is a sequence of instructions). They seemed to be naturally represented as 'code', as opposed to a binary format that is equivalent to the internal structures (e.g. syntax tree) of a parser. It is possible to do that, but a textual form seemed more natural. In a plain graph, it is not so important though, and for that a protobuf format would not get very complicated, that is true.

I don't think it would ease conversion too much though. It a converter, you typically have to read the input format into memory, do the conversion possibly in multiple passes, and then write out the result to a destination format. Directly building a flatbuffer or protobuf works for simple conversions, but not so much for complicated ones. In those cases you have to define some convenient in-memory structure independent of the source and target formats to manipulate the graph easily. We are currently refactoring our converters in this way.

I agree that protobuf has nice compatibility mechanisms, but keeping backward compatibility is always an important goal of Khronos standards. Also, migration tools need to be written even for protobuf based formats, and doing so will also be a priority for NNEF irrespective of the format.

**Comment by jnorwood** [comment]
On the math expressions ... Do you propose to extract expressions from other persisted models or export expressions from nnef to other persisted model formats during the conversions, or is this just for self-documentation for new operations while viewing the nnef file? 

On the convenient in-memory structure ...  Yes, I agree, but the end product of the protobuf format would be easier to get correct than having to figure out from the NNEF spec what constitutes a valid network description.  

Also, the generated access operations in a protobuf header  can be easily included in users' programs, which I suspect is  one of the main features that results in it getting supported in, for example, Netron.  Your semantic checks are still important, but could be run on the protobuf.

**Comment by jnorwood** [comment]
> define some convenient in-memory structure independent of the source and target formats

on the in-memory structures you use during conversion ...  possibly  exactly that could become a part of a protobuf definition.

**Comment by gyenesvi** [comment]
The math expressions could be part of NNEF which does not come from other models. For example when defining operations (either standard or custom), it could be possible to describe semantic checks and shape calculations using arithmetic/logical expressions. These expressions would be for the compiler, not for the execution engine (compile-time expressions, not run-time expressions). It is much more natural to describe such expressions as text when defining operations, as opposed to a binary format. The same goes for defining custom operations, it is not really the job of a converter, but that of a human introducing a new operation, who can do that easier in text form (such as compound fragment definitions in NNEF).

About validity: the protobuf format would not define a lot of semantic checks on the model. It would make parsing (syntactic) easier, but a lot of semantics would still have to be defined and checked. For example that the graph is correctly connected, the operation attributes are in valid ranges, or that shapes can be properly propagated through the graph and they match properly for arguments. And just as the protobuf parser can be integrated into any tool, the NNEF parser can be as well. We are working on an improved interface to make it easier to use and integrate.

The convenient in-memory structure for conversion is quite different from what it would look like in protobuf. It is in fact just some simple structures built from lists and dictionaries, which is much easier to work with that directly with the protobuf structures. In fact, in Python, protobuf support is quite cumbersome, as the structures are generated and added dynamically, so static code analyzers like pylint cannot see what members and methods are available, and neither can you manually inspect the code. It is actually quite a pain to use it in my experience.

**Comment by jnorwood** [comment]
Yes, I understand that your parser would still be providing the semantic validation.  I was only suggesting the protobuf or flatbuffer persistence format because I note that these appear to be commonly used by several network apps.  I think using something home-brew will make it harder to obtain support.

on the math expressions ... it is still unclear to me how  you intend them to be used and where they are required.  Are you saying they are just being uses to determine the shapes of the outputs for an operation?  If so, maybe just an output shape definition should be supported.

If they are just meant as self-documenting comments, and not something supported by the exchange translations, perhaps they should just be replaced by comments.

If they are intended to provide some sort of high level, network operation description language, maybe something that would be useful for display in the network diagrams or useful for generating code, then maybe all the user needs is some special form of comment ... like used by document generators.

**Comment by gyenesvi** [comment]
The math expressions could be part of operator schema definitions (like a network operation description language, as you say), like shapes of the outputs, hence translations need not handle it. The purpose would be to help compilers and the validation process of the network structure, by providing a more formal definition of shapes and what exactly needs to be validated. Some of this could be described in special comment strings inside a binary format, but in some cases a more tight integration might be required with the rest of the graph description to formulate constraints. Furthermore, if it's a special string, you need to parse it anyway..
