### ISSUE TITLE
Caffe conversion problems with BatchNorm

### ISSUE THREAD

**Issue by rgiduthuri** [KhronosGroup/NNEF-Tools#7]
The caffe converter is using '*' and '+' operations that are not supported by the NNEF spec.

Here is the prototxt that I used is from caffe model zoo: https://github.com/KaimingHe/deep-residual-networks/blob/master/prototxt/ResNet-50-deploy.prototxt

**Comment by gyenesvi** [comment]
I have pushed a fix to the branch `fix_batch_norm_export`. @rgiduthuri can you test it?

**Comment by gyenesvi** [comment]
This seems to be exporting well with the above example.
