### ISSUE TITLE
Caffe to NNEF: No support for Prelu's

### ISSUE THREAD

**Issue by neil-jones-work** [KhronosGroup/NNEF-Tools#72]
I'm trying to convert MTCNN to NNEF (and ultimately to openVX) but the Caffe converter doesn't support Prelu activations:

~/src/MTCNN_face_detection_alignment/code/codes/MTCNNv1/model$ caffe_to_nnef det1.prototxt --model det1.caffemodel 
Error: caffe_to_dog: No converter for: PReLU
Error: caffe_to_dog: No converter for: PReLU
Error: caffe_to_dog: No converter for: PReLU
Error: No converter for PReLU
Error: conv1_1: Corresponding targetdn not defined
Error: No converter for PReLU
Error: conv2_1: Corresponding targetdn not defined
Error: No converter for PReLU
Error: conv3_1: Corresponding targetdn not defined

https://github.com/kpzhang93/MTCNN_face_detection_alignment

**Comment by gyenesvi** [comment]
Indeed, this is missing from the converter, we'll add it soon.

**Comment by gyenesvi** [comment]
We have added prelu support, can you test it now?

**Comment by neil-jones-work** [comment]
Yes the model now successfully converts thanks!
IIRC there used to be an NNEF to openVX converter on the Khronos site, Is this still supported ? if not will openVX output be added to the NNEF converter ?

**Comment by gyenesvi** [comment]
It believe there was no official such converter. Where was that converter available?

**Comment by neil-jones-work** [comment]
This was what I was thinking of, but its AMD specific:


https://github.com/GPUOpen-ProfessionalCompute-Libraries/amdovx-modules/blob/develop/utils/model_compiler/README.md



Any plans for a more generic one ?



________________________________

**Comment by gyenesvi** [comment]
I believe the OpenVX group is working on a mechanism to import NNEF models into OpenVX, that can be implemented by vendors, but I cannot tell details about it until the spec is published.
