### ISSUE TITLE
Readme file is outdated 

### ISSUE THREAD

**Issue by syedaffanhamdani** [KhronosGroup/NNEF-Tools#78]
Conversion examples do not match the current supported arguments of the conversion tool. I was able to run the updated parser with following command
```
./nnef_tools/convert.py --input-framework=nnef \
                        --output-framework=tensorflow-pb \
                        --input-model=out/nnef/frozen_inception_v1/model.nnef.tgz \
                        --output-directory=out/tensorflow-pb/frozen_inception_v1.pb 
```

**Comment by gyenesvi** [comment]
Are you sure you have updated to the latest code? The code on github (the command line args in `convert.py`) seems to match the readme.

**Comment by syedaffanhamdani** [comment]
Okay, my bad! After pulling the latest code it is as you say. thanks.
