### ISSUE TITLE
missing shape 

### ISSUE THREAD

**Issue by hansely** [KhronosGroup/NNEF-Tools#83]
I've downloaded inception-resnetv2 model on the model zoo which was converted from tensorflow model. 
However, there is a variable named 'varaible_92' with empty shape attribute. 
Is this an error? If not, how is the shape calculated?

**Comment by gyenesvi** [comment]
If I understand correctly, you are saying that `shape = []`, so it is not missing, it is an empty array. It is not an error; the length of the array is the number of dimensions of a tensor, so it is a 0-dimensional tensor, which is a single scalar.

**Comment by hansely** [comment]
Oh I get it. Thanks!
