### ISSUE TITLE
Citing NNEF?

### ISSUE THREAD

**Issue by breandan** [KhronosGroup/NNEF-Tools#91]
What's the appropriate way to cite NNEF in an academic publication?

**Comment by gyenesvi** [comment]
In the body of the text, when you first mention NNEF you have to use the trademark as 'NNEF<sup>TM</sup>', and you should insert a footnote saying "NNEF and the NNEF logo are trademarks of the Khronos Group Inc." All other occurrences can just simply be 'NNEF' (without the TM) in the body of the text.

When you want to insert a bibliography item to reference the specification itself, you can just add a link to the Khronos website, maybe with the full name and the name of Khronos, like "Neural Network Exchange Format, The Khronos Group, https://www.khronos.org/nnef".

**Comment by gyenesvi** [comment]
Can I close this?
