### ISSUE TITLE
 Unsupported attributes in operation reshape

### ISSUE THREAD

**Issue by Alena19971993** [KhronosGroup/NNEF-Tools#98]
Hello. In file "NNEF-Tools/parser/cpp/include/nnef/flat/stdlib_protos.h" for operation "reshape" missing attributes (axis_start and axis_count)  which were added in https://www.khronos.org/registry/NNEF/specs/1.0/nnef-1.0.2.html 

1.0.1
![1.0.1](https://user-images.githubusercontent.com/22199728/64678578-88f36400-d482-11e9-8e43-044dad899b8e.png)

1.0.2
![1.0.2](https://user-images.githubusercontent.com/22199728/64679128-b856a080-d483-11e9-9337-96f6f3f4f184.png)

**Comment by gyenesvi** [comment]
You were right, I merged your pull request. However, all new operations added in version 1.0.2 (pad, tile, sin, cos, any_reduce, all_reduce) were also missing from this file, so I have also added those as well.

**Comment by gyenesvi** [comment]
Thanks for catching this!
